title: Daryle Bilog # your name (or website title) here
logo: "/daryle_profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have a Master of Science in Business Analytics from the Davis Eccles School of Business, University of Utah. 
  <br><br>
  I have a working and educational knowledge of SQL, R, and Python Programming Languages.
  <br><br>
  <a href="https://www.linkedin.com/in/daryle-bilog/">LinkedIn</a> | <a href="https://www.linkedin.com/in/daryle-bilog/">Resume</a>
